/* ══ PNG EXPORT ══ */
async function exportPNG(){
  const btn=document.getElementById('export-btn');
  // Check if anything is selected
  const totalSelected=Object.values(_selectedActs).reduce((s,a)=>s+a.length,0);
  if(totalSelected===0){
    btn.textContent='⚠ Add activities first!';
    setTimeout(()=>{btn.innerHTML='<span>⬇</span> Export as PNG';},2000);
    return;
  }
  btn.disabled=true;btn.innerHTML='<span style="animation:rot 1s linear infinite;display:inline-block">⟳</span> Generating...';

  // Build the hidden export canvas
  const trip=TRIP, meta=META;
  const itin=trip.itinerary||[];
  const exportEl=document.getElementById('export-canvas');
  if(!exportEl)return;

  exportEl.innerHTML=`
    <div class="ec-header">
      <div class="ec-dest">${trip.destination}</div>
      <div style="font-size:14px;color:#bfb49e;font-style:italic;margin:6px 0">${trip.tagline||''}</div>
      <div class="ec-meta">
        <span class="ec-pill">✈ ${meta.startFmt}</span>
        <span class="ec-pill">🏠 ${meta.endFmt}</span>
        <span class="ec-pill">📅 ${meta.days} Days</span>
        <span class="ec-pill">👥 ${meta.travelers} ${meta.travelers==1?'Guest':'Guests'}</span>
        <span class="ec-pill">💰 ${({budget:'Budget',moderate:'Moderate',luxury:'Luxury','ultra-luxury':'Ultra Luxury'})[meta.budget]||meta.budget}</span>
      </div>
    </div>
    ${itin.map((day,di)=>{
      const acts=_selectedActs[di]||[];
      if(!acts.length)return'';
      return `<div class="ec-day">
        <div class="ec-day-head">
          <div class="ec-day-badge">
            <div class="ec-day-n">${day.day}</div>
            <div class="ec-day-lbl">Day</div>
          </div>
          <div>
            <div class="ec-day-title">${day.title||'Day '+day.day}</div>
            <div class="ec-day-date">📅 ${day.date||''}</div>
          </div>
        </div>
        <div class="ec-acts">
          ${acts.map(a=>`
            <div class="ec-act">
              <div class="ec-act-emoji">${a.emoji||'📌'}</div>
              <div>
                <div class="ec-act-name">${a.name}</div>
                <div class="ec-act-cat">${a.category}${a.duration?' · '+a.duration:''}${a.entryFee?' · 🎟 '+a.entryFee:''}</div>
              </div>
            </div>`).join('')}
        </div>
      </div>`;
    }).join('')}
<div class="ec-footer">Generated by ai-trip-planner</div>`;

  // Move export-canvas to be visible temporarily for html2canvas
  exportEl.style.left='0';
  exportEl.style.top='0';
  exportEl.style.zIndex='-1';
  exportEl.style.position='fixed';

  try{
    await new Promise(r=>setTimeout(r,200)); // let DOM paint
    const canvas=await html2canvas(exportEl,{
      backgroundColor:'#111008',
      scale:2,
      useCORS:true,
      logging:false,
      width:800,
      windowWidth:900
    });
    const link=document.createElement('a');
    link.download=(trip.destination||'trip').replace(/[^a-zA-Z0-9]+/g,'-')+'-itinerary.png';
    link.href=canvas.toDataURL('image/png');
    link.click();
  }catch(e){
    alert('Export failed. Please try again.');
  }finally{
    exportEl.style.left='-9999px';
    exportEl.style.top='-9999px';
    exportEl.style.position='fixed';
    exportEl.style.zIndex='auto';
    btn.disabled=false;
    btn.innerHTML='<span>⬇</span> Export as PNG';
  }
}
